#!/usr/bin/env bash
# This script provides answers to the networking questions.

# Answer to the first question
echo "3" # LAN

# Answer to the second question
echo "2" # WAN

# Answer to the third question
echo "1" # Internet
