#!/usr/bin/env bash
# This script provides answers to the networking questions and fills the drawing.

# Answer to the first question (TCP box)
echo "1" # It is a protocol that is transferring data in a slow way but surely

# Answer to the second question (UDP box)
echo "2" # It is a protocol that is transferring data in a fast way and might loss data along in the process

# Answer to the third question (TCP worker)
echo "1" # Have you received boxes x, y, z?
