#!/usr/bin/env bash
# Short and Sweet Fix for Nginx to listen on port 80

# Configure Nginx to listen on port 80
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

