#!/usr/bin/env bash
# This script tells the story of each user from /etc/passwd.

while IFS=':' read -r username _ userid _ _ comment homedir shell; do
    echo "The user $username is part of the $userid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $comment"
done </etc/passwd
