#!/usr/bin/env bash
# This script displays "Best School" 10 times, but shows "Hi" on a new line after the 9th iteration.

counter=1
while [ "$counter" -le 10 ]
do
    if [ "$counter" -eq 9 ]; then
        echo "Hi"
    fi

    echo "Best School"
    ((counter++))
done
