#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443, and 80.

# Use sudo to install ufw
sudo apt-get install ufw

# Set IPV6 to yes in ufw config
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Disable and enable ufw to apply changes
sudo ufw disable
sudo ufw enable

# Set the default policies for incoming and outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

