#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school

# Use the ssh command to connect to the server with the private key
ssh -i ~/.ssh/school ubuntu@35.175.129.182
